name: responsive_navigation_bar

description: A responsive bottom navigation bar. Very beginner friendly. Feel free to contribute.
repository: https://github.com/nohli/responsive_navigation_bar
issue_tracker: https://github.com/nohli/responsive_navigation_bar/issues

topics:
  - bottomnavigationbar
  - bottombar
  - responsive
  - ui

screenshots:
  - description: 'Dark mode with text and animation'
    path: assets/animation-darkmode-with-text.gif
  - description: 'Light mode with text and animation'
    path: assets/animation-lightmode-with-text.gif
  - description: 'Dark mode with text'
    path: assets/darkmode-with-text.gif
  - description: 'Light mode with text'
    path: assets/lightmode-with-text.gif

version: 6.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
