name: responsive_navigation_bar
description: A responsive bottom navigation bar. Very beginner friendly. Feel free to contribute.

repository: https://github.com/nohli/responsive_navigation_bar
issue_tracker: https://github.com/nohli/responsive_navigation_bar/issues

topics:
  - bottomnavigationbar
  - bottombar
  - responsive
  - ui

version: 4.0.4

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
